##The website title
name: skydusk
url: http://skydusk.github.io
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: /skydusk
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: just another personal blog
##Some frequently used keywords on your website
keywords: windows, storage, crashplan, synology, backups, itunes

##define this for disqus comment support
disqus: skydusk

##set this to enable google analytics
#ga_id: UA-66844898-1
#ga_domain: http://skydusk.github.io

##Some commonly used links
links:
  facebook: username
  twitter: username
  email: info@skydusk.com
  github: username

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: off
